
topo_path: "./topo/RTopo-2.0.1_30sec_bos_fix_lowres_D3.nc" # path to topography
n_latitudes: 180 # number of latitudes (one will be added)
n_longitudes: 360 # number of longitudes (one will be added)
base_resolution: 300 # resolution at equator, km

use_existed_refinements: false

use_existed_jigsaw_mesh: false

mercator_resolution:
    do_mercator_refinement: false
    norhtern_boundary: 60
    norhtern_lowest_resolution: 22.5    
    southern_boundary: -60
    southern_lowest_resolution: 22.5

refine_along_equator:
    do_refine_along_equator: true
    lat_boundary: 3.5        # °N/S of the equator for the high-resolution nest
    resolution: 50           # km
    
refine_along_coastlines:
    do_refine_along_coastlines: false
    min_resolution: 10      # km, resolution at the coast 
    max_distance: 100      # km, distance from the coast
    min_length: 500        # km, min length of coastline
    averaging: 50          # km, smoothing coastline

refine_over_bathymetry:
    do_refine_over_bathymetry: false
    min_depth: 50      # meters
    min_resolution: 5  # km
    max_depth: 1500     # the base resolution won't be altered starting from this depth  

do_refine_within_regions: true

regions:
    - name: Denmark
      path: './kml/Denmark.kml' # path to the .kml file
      resolution: 100 # resolution of the inner region
    - name: Gibraltar
      path: './kml/Gibraltar.kml'
      resolution: 100
    # - name: Baffin
    #   path: './kml_Jones/Baffin.kml'
    #   resolution: 10
    # - name: Hudson
    #   path: './kml_Jones/Hudson.kml' # path to the .kml file
    #   resolution: 5 # resolution of the inner region
    # - name: CAA
    #   path: './kml_Jones/CAA.kml'
    #   resolution: 2
    # - name: Cardigan
    #   path: './kml_Jones/Cardigan.kml'
    #   resolution: 0.5
    # - name: Nares
    #   path: './kml_Jones/Nares.kml'
    #   resolution: 1
    # - name: Fury
    #   path: './kml_Jones/Fury.kml'
    #   resolution: 0.3
    # - name: Eclipse
    #   path: './kml_Jones/Eclipse.kml'
    #   resolution: 0.7
    # - name: Inglefield
    #   path: './kml_Jones/Inglefield.kml'
    #   resolution: 0.7

plot_region:
    # do_plotting: true
    # min_lat: 60
    # max_lat: 90
    # min_lon: -180
    # max_lon: 180
    # projection: 'NorthPolarStereo'
    # central_longitude: 0
    do_plotting: true
    min_lat: -60
    max_lat: 50
    min_lon: -100
    max_lon: 0
    projection: 'Mercator'
    central_longitude: 0
    

minimum_depth: 30 # the minimum allowed depth in any node (positive (!) value in meters)

levels: [0.0, -5.0, -10.0, -15.0, -20.0, -25.0, -30.0, -35.0, 
        -40.0, -45.0, -50.0, -55.0, -60.0, -65.0, -70.0, -75.0,
        -80.0, -85.0, -90.0, -95.0, -100.0, -110.0, -120.0,
        -130.0, -140.0, -150.0, -160.0, -170.0, -180.0, -190.0,
        -200.0, -220.0, -240.0, -260.0, -280.0, -300.0, -340.0,
        -380.0, -420.0, -460.0, -500.0, -540.0, -580.0, -620.0,
        -660.0, -760.0, -860.0, -1040.0, -1180.0, -1380.0,
        -1500.0, -1700.0, -1920.0, -2150.0, -2400.0, -2650.0,
        -2900.0, -3150.0, -3400.0, -3650.0, -3900.0, -4150.0,
        -4400.0, -4650.0, -4900.0, -5150.0, -5400.0, -5650.0,
        -6000.0, -6350.0]
    
